### ISSUE TITLE
Bug Report: Some words isn't match the time span tag.

### ISSUE THREAD

**Issue by YichuanSun** [oss-compass/compass-web#100]
When I read a project report, click the time span tag like "6个月", "1年"，the number of days in the website is not change, which is still show "90 天", although the real statistic data has shown.
![image](https://user-images.githubusercontent.com/30886176/227769392-678bc5bb-0b08-46b2-b707-2f4ef23d67e8.png)

90 days = 1 year? Is it another Chenping inequality? 🤣

**Comment by eyehwan** [comment]
Hi, @YichuanSun "90 days" in a sepcific metric means that the data in every measurement point is accumulated in the past 90 days. 
In the top right corner, the time window is related to how much data this community has over the past 6 M/1year .. you can see

**Comment by YichuanSun** [comment]
> Hi, @YichuanSun "90 days" in a sepcific metric means that the data in every measurement point is accumulated in the past 90 days. In the top right corner, the time window is related to how much data this community has over the past 6 M/1year .. you can see

Well...... Each time someone clicks the top right time span buttom, the website will show the corresponding diagram for the specific time span like "1年", while the figure description doesn't change at all...... I don't think it is a good idea. Anyway, thanks.

**Comment by eyehwan** [comment]
> while the figure description doesn't change at all

Because it is the definition of the metric, it would not be changed by time span in the top right cornor. 

@YichuanSun  You are welcomed to continue this discussion by wechat group of oss-compass: https://oss-compass.org/docs/zh/community/wechat/
