### ISSUE TITLE
Front End: Compass Badge Support（Compass 外链徽章支持）

### ISSUE THREAD

**Issue by normal-coder** [oss-compass/compass-web#150]
已讨论：
      - 旭日图有三个环，分别代表维度、Model、Metric
      - 每个环的比例：Model Metric 的占比
      - 颜色深浅：图表比例按照权重进行分布
      - 颜色差异：实现和未实现（未实现可归类为 Other）
 
---
2023-06 Update:

Badge 入口：报告页面右上角，提供 Shield、Small、Large 三种Badge ，对应提供 Markdown、HTML、超链接。

![16867867615733](https://foruda.gitee.com/images/1686786762657360844/5e23b4b8_551147.png)

Badge 样式如下：

![16868003370714](https://foruda.gitee.com/images/1686800337801294075/66ca0b45_551147.png)

链接资源定义格式：

```mermaid
flowchart LR
    subgraph 域名
        domain(https://oss-compass.org)
    end
    subgraph 报告对比路由
        route-report(report)
    end
    subgraph 报告哈希
        hash(hash)
    end
    subgraph 类型后缀
        ext(.svg/.png)
    end
    subgraph Badge 类型
        badge_type(shield/small/large)
    end
    subgraph 其他参数
        option_param(range=2Y)
    end
    domain-.-|/|route-report-.-|/|hash-.-ext-.-|?type=|badge_type-.-|&|option_param
```

Example:

```markdown
[![Compass Analyze](https://compass.gitee.com/report/CIDKA59K.svg?type=shield)](https://compass.gitee.com/report/CIDKA59K?ref=badge_shield)
```

**Comment by EdmondFrank** [comment]
![Image](https://github.com/oss-compass/compass-web/assets/13914416/9eb349d0-bd6a-4207-8e06-e2a9d2ad1be4)

**Comment by EdmondFrank** [comment]
![GroupActivity](https://compass.gitee.co/badge/sbfoool4.svg?metric=organizations_activity)
![Activity](https://compass.gitee.co/badge/sbfoool4.svg?metric=activity)
![Community](https://compass.gitee.co/badge/sbfoool4.svg?metric=community)
![CollabDevIndex](https://compass.gitee.co/badge/sbfoool4.svg?metric=collab_dev_index)
![Status](https://compass.gitee.co/badge/sbfoool4.svg)

https://compass.gitee.co/analyze/sbfoool4
