### ISSUE TITLE
[Compass Badge] Independent diagrams embedded pendant System Design

### ISSUE THREAD

**Issue by EdmondFrank** [oss-compass/compass-web#176]
Using echart-server as a backend for svg image rendering
```[tasklist]
### Tasks
- [ ] https://github.com/oss-compass/compass-web/issues/226
```

**Comment by EdmondFrank** [comment]
Preview demo

@nanzm @normal-coder @eyehwan 

collab_dev_index score chart:
https://compass.gitee.co/chart/sr7ldhna.svg?chart=line&metric=collab_dev_index&y_abs=1
![img](https://compass.gitee.co/chart/sr7ldhna.svg?chart=line&metric=collab_dev_index&y_abs=1)

collab_dev_index loc_frequency chart:
https://compass.gitee.co/chart/sr7ldhna.svg?chart=bar&metric=collab_dev_index&y_abs=1&field=lines_added_frequency
![img](https://compass.gitee.co/chart/sr7ldhna.svg?chart=bar&metric=collab_dev_index&y_abs=1&field=lines_added_frequency)

**Comment by eyehwan** [comment]
Looks great! As we discussed yesterday, some comments made by @normal-coder . I hope we could deploy it ASAP.
