### ISSUE TITLE
Improve mobile support for adding a community

### ISSUE THREAD

**Issue by HarelM** [oss-compass/compass-web#178]
Hi, thanks for this amazing tool!
I've tried to use this tool from a mobile device to add a new community and the UI is a bit problematic - repos names are cut off and the pick button is also covering some of the text.
I'm sure there are also other places where there are issue when using the mobile device.

**Comment by eyehwan** [comment]
@nanzm would you please take a look at this issue?

**Comment by nanzm** [comment]
Thank you for your feedback! I will make sure to allocate time to fix the issues related to mobile usage.

**Comment by nanzm** [comment]
![image](https://github.com/oss-compass/compass-web/assets/12454813/90479a92-b1ae-46d4-bc80-ea5061add512)
