### ISSUE TITLE
Detailed metrics dashboard development（详细化指标仪表盘开发）

### ISSUE THREAD

**Issue by poorfish** [oss-compass/compass-web#231]
![Image](https://github.com/oss-compass/compass-web/assets/8347925/97d996d9-7297-4984-950f-ce580dd05ebb)

![Image](https://github.com/oss-compass/compass-web/assets/8347925/f0ebaceb-9915-4cc6-a77b-acc448828f16)

![Image](https://github.com/oss-compass/compass-web/assets/8347925/15381ff5-39c1-4769-9138-3b12a72a3756)

设计稿：https://lanhuapp.com/link/#/invite?sid=lXnV0P4a
分享人: poorfish
团队名称: OSCHINA的团队
相关项目: OSS Compass
分组: 详细化指标
链接有效期: 20230912~20230926

**Comment by lishengbao** [comment]
**详细化指标需求, 以下指标根据用户选择范围统计**
**1. 首页仪表盘展示:**

> 贡献者指标

- 组织个数
- 贡献者个数
- 最高贡献的组织
- 最高贡献的贡献者

> Issue指标

- Issue总数
- Issue完成率
- 未响应Issue个数和比例(未响应Issue数 / Issue总数)
- Issue平均评论个数

> PR指标

- PR总数
- PR完成率
- 未响应PR个数和比例(未响应PR数 / PR总数)
- Commit总数

**2. 贡献者列表**

- 贡献者列表展示: 列表信息有用户名, 生态角色类型, 组织名, 贡献领域, 贡献量
- 贡献量展示: 根据生态角色类型, 领域类型, 组织划分的贡献量和比例；以及每个贡献者的贡献量和比率; 
- 组织展示: 展示每个组织的贡献量和比率
- 贡献者展示: 根据生态角色类型, 贡献领域, 组织划分的贡献者数量和比例

**4. Issue列表**

- Issue列表展示：列表信息有标题，URL，状态，创建时间，关闭时间，处理时长，首次响应时长，评论数量，标签，创建者，责任人
- Issue完成数量及比例：展示Issue各个状态的数量和比例
- Issue评论数量及比例

**5. PR列表**
- PR列表展示：列表信息有标题，URL，状态，创建时间，关闭时间，处理时长，首次响应时长，评论数量， 标签，创建者，审查者，合并者
- PR完成数量及比例：展示PR各个状态的数量和比率
- PR评论数量及比例


**6. 贡献者列表, Issue列表, PR列表权限定义**

- 社区管理者用户可以查看全部数据
- 其他用户只能查看最近6个月数据, 或者 通过联系我们手动开发
