### ISSUE TITLE
Navigation bar on the homepage of the oss-compass.org updates (主页导航栏更新)

### ISSUE THREAD

**Issue by JuliaZhou2022** [oss-compass/compass-web#256]
- [ ] 导航栏加“文档”一栏，把部署文档、用户文档等内容放在这个页面，包括之前的评估模型页面。用户文档需要补充。

- [ ] 导航栏名称和顺序调整：（中文）文档>项目>Compass实验室>加入社区>动态>关于，（英文）Documentation>Projects>Compass Lab>Join Community>News>About

**Comment by hncslwx** [comment]
建议在“探索”页面做几点修改：
1. 在“探索”页面的上方增加搜索框；
2. 把在“更多仓库”里面才展示的项目分类列表，上移到“探索”的第一个页面。
