### ISSUE TITLE
compass.gitee.com 显示不出来数据

### ISSUE THREAD

**Issue by TommyLemon** [oss-compass/compass-web#52]
oss-compass.org 能显示 APIJSON 的报告
https://github.com/Tencent/APIJSON/issues/518
![image](https://user-images.githubusercontent.com/5738175/220563024-017d3733-d499-4d48-adcb-d69d05934cc4.png)
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/5738175/220536138-8dbe4bd3-5465-49f8-938d-c71bd84690b7.png">

compass.gitee.com 就没有显示出来具体的指标数据，这两天试了 7 次以上都是这样，看起来两个域名背后的服务是独立的。
https://compass.gitee.com/analyze?label=https%3A%2F%2Fgitee.com%2FTencent%2FAPIJSON&level=repo&range=Since%202000
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/5738175/220562585-199dff17-a885-41d6-b5fd-2d338a79a7a2.png">

https://compass.gitee.com/analyze?label=https%3A%2F%2Fgithub.com%2FTencent%2FAPIJSON&level=repo&range=Since%202000
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/5738175/220562706-199c9ae9-53cf-4cb9-89c6-13c3704b34fa.png">

**Comment by EdmondFrank** [comment]
duplicate issue https://github.com/oss-compass/compass-projects-information/issues/146#issue-1594661150
