### ISSUE TITLE
[Bug]项目链接多了就会向上挤出显示区域

### ISSUE THREAD

**Issue by TommyLemon** [oss-compass/compass-web#57]
如图
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/5738175/221114552-06723eca-39a7-43be-a195-57e0626d3994.png">

https://oss-compass.org/analyze?label=https%3A%2F%2Fgithub.com%2FTencent%2FAPIJSON&label=https%3A%2F%2Fgithub.com%2Fmybatis%2Fmybatis-3&label=https%3A%2F%2Fgithub.com%2Fgrpc%2Fgrpc-java&label=https%3A%2F%2Fgithub.com%2Fapache%2Fdubbo&level=repo&range=Since%202000&label=https%3A%2F%2Fgithub.com%2Fspring-projects%2Fspring-boot&label=https%3A%2F%2Fgithub.com%2Fspring-projects%2Fspring-framework

**Comment by TommyLemon** [comment]
org 已经好了，gitee 的还没好

**Comment by eyehwan** [comment]
@TommyLemon thanks for your comment, you can check it now, should be fixed.

**Comment by TommyLemon** [comment]
It has been fixed, thx~
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/5738175/221463385-0385102b-80a4-45d2-a781-03e7ab398f50.png">
