### ISSUE TITLE
Front End: Distinguish positive and negative metrics(正负向指标区分)

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-web#67]

**Comment by nanzm** [comment]
社区服务与支撑
    Issue 首次响应时间  (负向)
    Bug 类 Issue 处理时间  (负向)
    PR 处理时间  (负向)
活跃度
    更新于  (负向)

**Comment by poorfish** [comment]
![Image](https://user-images.githubusercontent.com/8347925/224654835-1b066458-d172-495d-826c-d8b602f3d270.png)

**Comment by normal-coder** [comment]
文字变更（正向化指标、负向化指标）
