### ISSUE TITLE
Front End: Trending Page Refactor(趋势页面重构)

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-web#72]
1. 优化整体展示
2. 加上项目的简介

**Comment by eyehwan** [comment]
https://github.com/trending

**Comment by poorfish** [comment]
预览个初稿，项目简介部分待讨论
![Image](https://user-images.githubusercontent.com/8347925/224653802-7def5907-ad9f-4ad4-afa7-bd6cc63931aa.png)

**Comment by normal-coder** [comment]
- UI reflects the total number of screens and the current number of screens (back-end control gives the number)
- Trend name changed to Weekly Trend

**Comment by normal-coder** [comment]
Provide specific implemented algorithmic logic @EdmondFrank @eyehwan

**Comment by poorfish** [comment]
![Image](https://user-images.githubusercontent.com/8347925/225190380-18369bce-2efa-455d-8831-9313ed760b2d.png)

**Comment by eyehwan** [comment]
![Image](https://user-images.githubusercontent.com/1535756/228150007-44d1e66b-4230-4f9d-8fcc-f0b3df2d7de4.png)
