### ISSUE TITLE
Front End Dev: Technical seminar weekly meeting landing page (技术研讨周会头部入口)

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-web#74]
adding meeting page information.

**Comment by normal-coder** [comment]
- `Meetup` 改为  `Metting`
- 在主 Web 工程、document-website 工程网站导航 `社区` 下拉菜单中加入 `Meeting` 菜单项

@nanzm

**Comment by nanzm** [comment]
下拉菜单  已处理
