### ISSUE TITLE
Front End Design: Distinguish code repository types on Community level dashboard(在看板区分代码仓类型)

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-web#82]
https://compass.gitee.com/analyze?label=phpunit&level=community

**Comment by poorfish** [comment]
![Image](https://user-images.githubusercontent.com/8347925/226565743-1b069dc1-d1cc-48d9-b92d-6865f15c7745.png)

**Comment by EdmondFrank** [comment]
deployed to beta environment
