### ISSUE TITLE
Front End：Community level problem tracking(社区level问题跟踪)

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-web#85]

**Comment by nanzm** [comment]
全屏图表拆分， 软件制品仓（Software Artifact Repository） 和  社区治理仓（Governance Repository）

**Comment by coder-sett** [comment]
Compass 多仓社区level问题链接：https://shimo.im/file-invite/mC2WTKP65ckmXtg2Wqh4iP212NOZ6/

**Comment by EdmondFrank** [comment]
backend has added a "type" field to the metrics model query.

**Comment by eyehwan** [comment]
制品仓、治理仓指标分类显示，使用全局变量开关。
